default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: email_parser_development

test:
  <<: *default
  database: email_parser_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %> # Created when linking database to app
  encoding: unicode
  pool: 5
